### ISSUE TITLE
Package not found in the registry

### ISSUE THREAD

**Issue by MotionPhix** [SidVerson/base-vue-phone-input#1]
I am getting an error when I run `npm install basic-vue-phone-input`

The error says:

**npm error 404 Not Found - GET https://registry.npmjs.org/basic-vue-phone-input - Not found**

**Comment by SidVerson** [comment]
> npm error 404 Not Found

try 

`npm config set registry`

**Comment by aoor9** [comment]
@MotionPhix That's because the package name starts with `base-`, not` basic-`.
@SidVerson Because of this, you should update the `README` file. And also, the repository's name and the one in `package.json` are different. They need to be the same.
